### ISSUE TITLE
Minimal example in the README.md

### ISSUE THREAD

**Issue by sujeongkim** [proroklab/gnngls#1]
I have two questions regarding the example in the README file.

```
python generate_instances.py 10 500 data
python preprocess_dataset.py data --n_train 400 --n_val 50 --n_test 50
```

1. The first command only creates 10 samples. Based on the second line, I guess it should have been `python generate_instances.py 500 10 data`?

2. When I tried the first command as is (10 samples with 500 nodes), it did not finish even after 10-12 hours. How much time is expected (in general), as number of nodes increases?

**Comment by Jaghov** [comment]
I seem to have the same issue with the script not generating any samples. It seems as though the solver gets stuck. 

Would appreciate any help in this.

**Comment by ben-hudson** [comment]
Hi, I made a mistake in the example - will update asap. You should generate 500 samples with 10 nodes. Labeling a set of 500 node samples will take a *very* long time. Keep in mind that this is still a minimal example, and we had a much larger training set in our paper.

**Comment by ben-hudson** [comment]
Fixed the minimal example in [this commit](https://github.com/proroklab/gnngls/commit/05b5aa1b166815f1404d7f01b40b59f6d0554237).
